In [1]:
import torch
import numpy as np
import time

# setting up for AMD chips 
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# setting up for chips Apple silicon
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps


In [ ]:
# generates 10 samples with the given probabilities.
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, 10, True)
print(samples)

tensor([1, 0, 1, 1, 1, 0, 1, 0, 0, 1])


In [ ]:
# concatenates two tensors
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), 0)
print(out)

tensor([1, 2, 3, 4, 5])


In [ ]:
# create a tensor with lower diagonal elements set to 1 
out = torch.tril(torch.ones(5,5))
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [ ]:
# create a tensor with upper diagonal elements set to 1 
out = torch.triu(torch.ones(5,5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])
