In [2]:
import torch
import numpy as np
import time

# setting up for AMD chips 
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# setting up for chips Apple silicon
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps


In [ ]:
# Use `masked_fill` to replace values where `mask` is True with `-inf`
# This means all values above the diagonal become `-inf`
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
# computes the exponential of each element in the input tensor.
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 3D tensor filled with zeros, with shape (2, 3, 4)
# Transpose the tensor: swap dimensions 0 and 2
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [ ]:
# Create three 1D tensors
# Stack the tensors along dimension 0 (rows)

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), 0)
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Create a sample input tensor with three elements
# Define a linear layer with input size 3 and output size 3, without bias


import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.7183, -3.9471,  5.1937], grad_fn=<SqueezeBackward4>)


In [ ]:
# Create a 1D tensor with three elements

import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)  

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [12]:
vocab_size = 1000
embeding_dim = 100
embedding = nn.Embedding(vocab_size, embeding_dim)

input_indices =torch.LongTensor([1,5,3,2])

embeded_output = embedding(input_indices)
print(embeded_output.shape)
print(embeded_output)

torch.Size([4, 100])
tensor([[-0.2342, -0.1424,  0.4821, -0.7892,  0.9484, -0.1277,  1.3946, -1.4655,
          0.3696, -0.9044, -0.5586,  0.3756,  0.0928, -0.5791, -0.4634, -0.9792,
         -0.4334, -0.0727, -0.9619,  0.3733,  1.3778, -1.4638,  0.7241, -1.1169,
          0.2622,  0.8205,  2.2998,  0.6449,  0.3855, -0.6064, -0.2542, -0.3373,
          0.4267, -0.6064,  0.5348,  0.5035,  0.3224,  1.0073, -0.2294, -0.3965,
          0.5074,  0.0812,  0.0940,  0.2620, -0.2138, -0.9245,  0.8130, -0.9175,
         -1.7313, -2.0542,  1.0113, -1.7825, -0.6565,  1.0601, -1.0156, -1.5445,
         -1.9709,  1.0898, -1.6185,  0.5036,  0.5700,  0.4504, -0.0212,  1.5864,
          0.0214,  1.1140, -0.3475,  0.1621,  1.5676,  0.0864,  0.1103, -0.0956,
         -0.0554, -0.5018,  1.2076,  0.1467,  0.4799,  0.4584,  1.2803, -0.8590,
         -0.4092, -1.2753,  1.0044, -1.5770,  1.0725,  0.0031, -0.8096,  0.5631,
         -0.1233,  0.8747, -2.3007,  0.7647,  0.7230,  0.6739,  0.4575,  1.1258,
       

In [13]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [14]:
int_64 = torch.randint(1, (3,2)).float()

float_32 = torch.rand(2,3)

result = torch.matmul(int_64, float_32)
print(result)



tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
