In [1]:
import torch
import numpy as np
import time

# setting up for AMD chips 
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# setting up for chips Apple silicon
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps


In [2]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.4f}")

Elapsed time: 0.0004


In [3]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, 10, True)
print(samples)

tensor([1, 0, 1, 1, 1, 0, 1, 0, 0, 1])


In [4]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), 0)
print(out)

tensor([1, 2, 3, 4, 5])


In [5]:
out = torch.tril(torch.ones(5,5))
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [6]:
out = torch.triu(torch.ones(5,5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])
