In [1]:
import torch

In [ ]:
# get a tensor of size 6, with random integers between -100 and 100
randint = torch.randint(-100, 100, (6,)) 
randint

tensor([-57,  42,  41,  -9, -29,  -8])

In [ ]:
# get a tensor 2D, with defined values
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [ ]:
# get a tensor of size 2x3, with zeros
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# get a tensor of size 3x4, with ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# get a tensor of size 2x3 with no values
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# create a tensor with values [0,1,2,3,4]
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
# create a tensor with values between 3 and 10, with a step of 5 
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [ ]:
# create a tensor with logarithm values between 10^-10 and 10^10, with 5 steps
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
# create a tensor of size 5 with diagonal values of 1 and rest in zeros
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:

# create a tensor of size 2x3 with no specific values
# dtype=torch.int64 argument specifies that the data type of the tensor elements should be 64-bit integers.
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])