In [2]:
import torch
import numpy as np
import time

# setting up for AMD chips 
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# setting up for chips Apple silicon
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps


In [3]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.4f}")

Elapsed time: 0.0002


In [4]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, 10, True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), 0)
print(out)

tensor([1, 2, 3, 4, 5])


In [6]:
out = torch.tril(torch.ones(5,5))
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [7]:
out = torch.triu(torch.ones(5,5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [9]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), 0)
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.2007, -0.2275, -7.9533], grad_fn=<SqueezeBackward4>)


In [14]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)  

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [16]:
vocab_size = 1000
embeding_dim = 100
embedding = nn.Embedding(vocab_size, embeding_dim)

input_indices =torch.LongTensor([1,5,3,2])

embeded_output = embedding(input_indices)
print(embeded_output.shape)
print(embeded_output)

torch.Size([4, 100])
tensor([[-1.1251,  0.5125, -0.7783,  1.6219,  1.5519,  0.1360,  2.6868,  0.6217,
          0.4105, -0.5470,  0.2962,  0.8561,  0.1099,  1.9029, -1.7326,  0.6690,
          0.2878, -0.8205,  0.1691,  0.5608, -0.1537, -0.8322,  1.4843,  0.7101,
          0.3382, -1.3943, -0.5206,  0.9570,  0.7294, -0.4121, -0.1984,  0.6037,
         -0.3845, -0.3648,  1.0655,  0.6682, -0.8470,  1.2346, -2.2213,  0.0669,
         -1.7979, -0.5943, -0.2869,  2.2422, -1.0460,  0.0763, -0.9950,  0.4626,
         -1.6690, -0.3267,  0.8637,  0.9545,  2.6320, -0.2676,  1.2551, -0.0221,
          1.7466, -1.0541,  1.6902, -2.6598, -0.3974, -1.8263, -0.3484, -0.0360,
         -0.9820, -1.7203,  0.2103,  0.8664,  1.1037,  2.0499,  0.3561,  0.3010,
          2.5126, -1.1292, -0.8071,  1.2102,  1.3530, -0.4309, -1.2000, -0.5592,
          0.9486, -0.2034, -1.9461,  0.1815, -0.7173,  0.6356,  0.2765, -1.1611,
         -1.0791,  0.3204,  0.7836,  1.9641,  0.4604,  1.1143,  0.7760,  0.0946,
       

In [ ]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(torch.matmul(a,b))